# Generated by Django 4.1.4 on 2022-12-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='salon',
            name='lon',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
    ]
