# Generated by Django 4.1.4 on 2022-12-09 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodOfTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.TimeField(verbose_name='Время начала')),
                ('end_period', models.TimeField(verbose_name='Время завершения')),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.periodoftime', verbose_name='Время записи'),
        ),
    ]
